<?php

namespace App\Form;

use App\Entity\Agent;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentEditType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->remove('password')
			->remove('clients')
//			->add('clients', EntityType::class, array(
//				'class' => Client::class,
//				'choice_label' => 'fullName',
//				'attr' => array('class' => 'select2'),
//				'multiple' => true
//			))
		;
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => Agent::class,
		]);
	}

	public function getParent() {
		return AgentType::class ; // TODO: Change the autogenerated stub
	}
}
