<?php

namespace App\Form;

use App\Entity\Agent;
use App\Entity\Client;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
           ->add('clients', EntityType::class, array(
           	'class' => Client::class,
            'choice_label' => 'fullName',
            'attr' => array('class' => 'select2'),
            'placeholder' => 'Ajouter des clients',
            'multiple' => true
           ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Agent::class,
        ]);
    }

    public function getParent() {
	    return UserType::class; // TODO: Change the autogenerated stub
    }
}
