<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Client1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mail', EmailType::class, array(
            	'label' => 'Email',
            	'attr' => array('class' => 'form-control form-control-lg ', 'placeholder' => 'Email')
            ))
            ->remove('agent')
//	        ->remove('password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
    public function getParent() {
	    return UserType::class; // TODO: Change the autogenerated stub
    }
}
