<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Fiche;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EditFicheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('client', EntityType::class, array(
	            'label' => 'Liste des Clients',
	            'placeholder' => 'Liste des Clients',
	            'attr'=> ['class' => 'select2 form-control custom-select', 'style' => 'width: 100%; height:36px;'],
	            'help' => 'Ce champ est obligatoire',
	            'help_attr' => ['class' => 'form-text text-muted'],
            	'class' => Client::class,
	            'choice_label' => 'username'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Fiche::class,
        ]);
    }

    public function getParent() {
	    return FicheType::class; // TODO: Change the autogenerated stub
    }
}
